version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "bot"
      POSTGRES_USER: "bot_user"
      POSTGRES_PASSWORD: "bot_user"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"